title: BioNotes.Org
description: Biology, ai, math, and more
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
include: 
  - _papers
  - _other
  - _business
  - _comp
  - _history
  - _marketing
plugins:
  - jekyll-sitemap
