title: BioNotes.Org
description: Notes on biology, deep learning, math, and other interests
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
include: 
  - _papers
  - _other
  - _business
  - _comp
  - _history
  - _marketing
plugins:
  - jekyll-sitemap
