title: BioNotes.Org
description: An education in 21st century biology
show_downloads: false
google_analytics:
theme: jekyll-theme-architect
include: 
  - _papers
  - _other
  - _comp
plugins:
  - jekyll-sitemap
